# Python script to uploade the full_text string wiht their embeddings to Huggingface
# Enter yout HF_TOKEN in the .env file: HF_TOKEN=hf....
# Adapt the location of the parquet file, username and reponame.
#
# Run with: uv run python search_x_likes/upload_to_huggingface.py
#
# The parquet file with embeddings is generated by the script search_x_likes/embed_posts.py


import os

import pandas as pd
import pyarrow.parquet as pq
from datasets import Dataset
from dotenv import load_dotenv

# Load .env file
load_dotenv()

PARQUET_FILE: str = "./data/embeddings.parquet"
USER_NAME = "cast42"  # Replace with your Hugging Face username
REPO_NAME = "x_likes"  # Change to your dataset name


def main() -> None:
    df = pd.read_parquet(PARQUET_FILE)
    print(df.columns)

    table = pq.read_table(PARQUET_FILE)
    ds = Dataset(table)

    # Get the Hugging Face token from the .env file
    hf_token = os.getenv("HF_TOKEN")

    if not hf_token:
        raise ValueError("HF_TOKEN is not found in the .env file.")

    # Dataset path and repository details
    full_repo_name = f"{USER_NAME}/{REPO_NAME}"  # Format: username/repo_name

    ds.push_to_hub(full_repo_name, token=hf_token)

    print(f"Dataset successfully uploaded to: https://huggingface.co/datasets/{full_repo_name}")


if __name__ == "__main__":
    main()
