site_name: search-x-likes
repo_url: https://github.com/cast42/search-x-likes
site_url: https://cast42.github.io/search-x-likes
site_description: Search posts from x that have liked yourself usign the archive download files
site_author: Lode Nachtergaele
edit_uri: edit/main/docs/
repo_name: cast42/search-x-likes
copyright: Maintained by <a href="https://cast42.com">Florian</a>.

nav:
  - Home: index.md
  - Modules: modules.md
plugins:
  - search
  - mkdocstrings:
      handlers:
        python:
          paths: [search_x_likes]
theme:
  name: material
  feature:
    tabs: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/cast42/search-x-likes
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/search-x-likes

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
